# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('products_app', '0003_auto_20160604_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('date_booking', models.DateTimeField(verbose_name='Fecha de la Consulta')),
                ('adress', models.CharField(max_length=500, verbose_name='Direccion')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('species', models.CharField(max_length=100, verbose_name='Especie')),
                ('breed', models.CharField(max_length=100, verbose_name='Raza')),
                ('conditions', models.TextField(max_length=5000, verbose_name='Razon de la consulta')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('hembra_normal', 'Hembra Normal'), ('hembra_esterilizada', 'Hembra Esterilizada'), ('macho_normal', 'Macho Normal'), ('macho_esterilizado', 'Macho Esterilizado')], max_length=20, null=True, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('adress', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserVeterian',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('adress', models.CharField(max_length=500, verbose_name='Direccion')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='user_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.UserCustomer', verbose_name='Dueno'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.Pet', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(to='products_app.Product'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.UserCustomer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_veterian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.UserVeterian', verbose_name='Veterinario'),
        ),
    ]
