# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Authorization Code')),
                ('ref_code', models.CharField(blank=True, max_length=100, verbose_name='Codigo de referencia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('status', models.CharField(blank=True, choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('fallo_en_el_pago', 'Error de Pago')], max_length=20, null=True, verbose_name='Estatus del pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.RemoveField(
            model_name='usercustomer',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userveterian',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name_plural': 'Mascotas'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pet_customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='products',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_veterian',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user_customer',
        ),
        migrations.DeleteModel(
            name='UserCustomer',
        ),
        migrations.DeleteModel(
            name='UserVeterian',
        ),
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.Booking', verbose_name='Reserva Relacionada'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.Customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking_app.Customer', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking_app.Customer', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
