# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('booking_app', '0002_auto_20160616_1158'),
    ]

    operations = [
    ]
