# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('booking_app', '0003_auto_20160620_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('auth_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Authorization Code')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking_app.Booking', verbose_name='Rserva Relacionada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('status', models.CharField(blank=True, choices=[('pagado', 'Pagado'), ('fallo_en_el_pago', 'Error de Pago')], max_length=20, null=True, verbose_name='Estatus del pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
