# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('booking_app', '0005_auto_20160628_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AddField(
            model_name='pet',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking_app.Customer', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
