# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('booking_app', '0006_auto_20160628_1456'),
    ]

    operations = [

        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('fallo_en_el_pago', 'Error de Pago')], max_length=20, null=True, verbose_name='Estatus del pedido'),
        ),
    ]
