# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('booking_app', '0007_auto_20160629_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo de referencia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='auth_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Authorization Code'),
        ),
    ]
