# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Consultas'},
        ),
    ]
