# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0002_auto_20160630_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('error_pago', 'Error de Pago')], max_length=20, null=True, verbose_name='Estatus del pedido'),
        ),
    ]
