# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0003_auto_20160630_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='birthday',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(default=0, max_length=5000, verbose_name='Edad'),
            preserve_default=False,
        ),
    ]
