# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0009_auto_20160720_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pet',
            field=models.ManyToManyField(blank=True, null=True, to='app_booking.Pet'),
        ),
    ]
