# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0010_auto_20160722_1051'),
        ('app_booking', '0010_auto_20160721_1546'),
    ]

    operations = [
    ]
