# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0011_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_booking.Booking', verbose_name='Mascota'),
        ),
    ]
