# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default='Descripcion del producto ...', max_length=5000),
        ),
    ]
