# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_auto_20160604_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Descripcion del producto ...', max_length=5000),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default='Descripcion de la categoria de producto ...', max_length=5000),
        ),
    ]
