# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=40)),
                ('person_email', models.EmailField(max_length=40)),
                ('message_subject', models.CharField(max_length=40)),
                ('message_content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
