# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='date_created',
        ),
    ]
