# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Publicar')),
                ('rating', models.IntegerField(default=5)),
                ('description', models.TextField(default='Escribe aqui la descripcion del Veterinario.', max_length=5000)),
            ],
        ),
    ]
