# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu_link', models.CharField(max_length=20)),
                ('headline', models.TextField(default='Headline...', max_length=5000)),
                ('short_description', models.TextField(default='Descripcion corta ...', max_length=5000)),
                ('long_description', models.TextField(default='Descripcion larga ...', max_length=5000)),
                ('image', models.ImageField(upload_to='static/images/services_app')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
        ),
    ]
