# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0006_auto_20160606_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('opinion', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='services_app/customers_display')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
        ),
        migrations.CreateModel(
            name='VetsDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='services_app/vets_display')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
        ),
    ]
