# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0009_auto_20160608_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='long_description',
            field=ckeditor.fields.RichTextField(default='Descripcion larga ...', max_length=5000),
        ),
    ]
