# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0010_auto_20160608_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetsdisplay',
            name='bio',
            field=models.TextField(default='bio', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetsdisplay',
            name='subtitle1',
            field=models.CharField(default='subtitle1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetsdisplay',
            name='subtitle2',
            field=models.CharField(default='subtitle2', max_length=100),
            preserve_default=False,
        ),
    ]
