# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0011_auto_20160630_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetsdisplay',
            name='bio',
            field=models.TextField(max_length=750),
        ),
    ]
