# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0012_auto_20160630_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='menu_link',
            field=models.CharField(max_length=30),
        ),
    ]
